import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ background: 'var(--background)', minHeight: '100vh' }}
      >
        {children}
        {/* <footer className="header-block" style={{ borderRadius: '0 0 18px 18px', marginTop: 40, fontSize: 18, justifyContent: 'center' }}>
          © 2024 ¿Qué me pongo? | Hecho con ♥
        </footer> */}
      </body>
    </html>
  );
}
